app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from app.config import Config
from flask_login import LoginManager

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()

executed = False

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    db.init_app(app)
    login_manager.init_app(app)
    migrate.init_app(app,db)
    
    from .views import view
    from .model import Usuario, Rol
    from werkzeug.security import generate_password_hash
    app.register_blueprint(view, url_prefix="/")

    with app.app_context():
         if not Rol.query.filter_by(rol='admin' ).first():
             rol_admin = Rol(rol = 'admin')
             rol_user = Rol(rol='usuario')
             db.session.add(rol_admin)
             db.session.add(rol_user)
             db.session.commit()

         if not Usuario.query.filter_by(usuario='admin').first():
             usuario = Usuario(
                 usuario='admin',
                 correo='admin@example.com',
                 clave= generate_password_hash('admin'),
                 rol_id = Rol.query.filter_by(rol="admin").first().id
             )
             db.session.add(usuario)
             db.session.commit()

    return app

app/views.py
from flask import Blueprint, render_template, request, send_from_directory, url_for, redirect, flash
from werkzeug.utils import secure_filename
from werkzeug.security import generate_password_hash, check_password_hash
from . import login_manager, db
import uuid
from  .model import Catalogo, db, Producto, Usuario, Rol
import os
from .config import Config
from flask_login import login_user, current_user, logout_user, login_required

view = Blueprint('view', __name__)

IMAGE_EXTENSION = {'jpg', 'jpeg'}

@login_manager.user_loader
def load_user(user_id):
    return Usuario.query.get(int(user_id))

def verify_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in IMAGE_EXTENSION

@view.route('/iniciar_sesion', methods=['GET', 'POST'])
def iniciar_sesion():
    if request.method == 'POST':
        usuario_correo = request.form['usuario_correo']
        clave = request.form['clave']
        if not usuario_correo or not clave:
            flash('No se ingresaron los valores')
        usuario = Usuario.query.filter((Usuario.usuario==usuario_correo)| (Usuario.correo==usuario_correo)).first()
        if usuario:
            if check_password_hash(usuario.clave, clave):
                login_user(usuario)
            else:
                flash ('La contraseña es incorrecta')
        else:
            flash('El usuario no existe')
    return redirect(url_for('view.Panel'))

@view.route('/cerrar_sesion', methods=['GET', 'POST'])
def cerrar_cuenta():
    logout_user()
    return redirect(url_for('view.IndexPage'))

@view.route('/crear_cuenta', methods=['GET','POST'])
def crear_cuenta():
    if request.method == 'POST':
        nombre_usuario = request.form['usuario']
        correo = request.form['correo']
        clave = request.form['clave']
        if not nombre_usuario or not correo or not nombre_usuario:
            flash("Complete los campos")
        if Usuario.query.filter_by(usuario=nombre_usuario).first():
            flash('El usuario esta en uso')
        if Usuario.query.filter_by(correo=correo).first():
            flash ('El correo esta en uso')
        else:
            usuario = Usuario(usuario=nombre_usuario , correo=correo, clave=generate_password_hash(clave), rol_id = Rol.query.filter_by(rol="usuario").first().id)
            db.session.add(usuario)
            db.session.commit()
            login_user(usuario)
            return redirect(url_for('AdminPage'))
        return  redirect(url_for('view.IndexPage'))
    return render_template('auth/crear_cuenta.html')


@view.route('')
@view.route('/')
def IndexPage():
    return render_template('index.html')

@view.route('/panel', methods=['GET', 'POST'])
def Panel():
    catalogos = Catalogo.query.all()
    return render_template('/admin/index.html', catalogos=catalogos)

@view.route('/crate_catalogo', methods=['GET', 'POST'])
def CreateCatalogo():
    if request.method == 'POST':
        imagen = request.files['portada']
        titulo = request.form['titulo']
        detalle = request.form['detalle']
        secure_portada = secure_filename(imagen.filename)
        ext = secure_portada.rsplit('.', 1)[1].lower()
        new_portada = f'{uuid.uuid4()}.{ext}'
        imagen.save(os.path.join(Config.UPLOAD_FOLDER,new_portada))
        catalogo = Catalogo(titulo=titulo, detalle=detalle, portada=new_portada)
        db.session.add(catalogo)
        db.session.commit()
        print (new_portada)
        print (titulo)
        print (detalle)
    return redirect(url_for('view.AdminPage'))

@view.route('/eliminar_categoria/<int:id>')
@login_required
def DeleteCatalogo(id):
    if current_user.rol.rol != 'admin':
        flash('No se puede realizar esta operación')
        return redirect(url_for('view.Panel'))
    else:
        catalogo = Catalogo.query.filter_by(id=id).first()
        if catalogo:
            db.session.delete(catalogo)
            db.session.commit()
            os.remove(os.path.join(Config.UPLOAD_FOLDER, catalogo.portada))
            flash('Elimación correcta')
        else:
            flash('No se encontro elemento')
            return redirect(url_for('view.Panel'))

@view.route('/detail_catalogo/<int:id>')
def DetailCatalogo(id):
    catalogo = Catalogo.query.filter_by(id=id).first()
    if catalogo:
        return catalogo.titulo
    else:
        return "No existe"

@view.route('/update_catalogo/<int:id>', methods=['GET', 'POST'])
def UpdateCatalogo(id):
    catalogo = Catalogo.query.filter_by(id=id).first()
    if catalogo:
        if request.method == 'POST':
            return "cambios realizados"
        else:
            print (catalogo)
            return render_template('index.html', catalogo=catalogo)
    else:
        return "No existe te regresaremos al inicio"
    
@view.route('/agregar_producto', methods=['GET','POST'])
def agregar_producto():
    if request.method == 'POST':
        titulo = request.form['titulo']
        detalle = request.form['detalle']
        catalogo = request.form['catalogo_id']
        portada = request.files['portada']
        secure_portada = secure_filename(portada.filename)
        ext = secure_portada.rsplit('.', 1)[1].lower()
        new_portada = f'{uuid.uuid4()}.{ext}'
        portada.save(os.path.join(Config.UPLOAD_FOLDER,new_portada))
        producto = Producto(titulo=titulo, detalle=detalle, catalogo_id=catalogo, portada=new_portada)
        db.session.add(producto)
        db.session.commit()

    return redirect(url_for('view.Panel'))

@view.route('/productos')
def productos():
    catalogos = Catalogo.query.all()
    productos = Producto.query.order_by(db.func.random()).all()
    return render_template('catalogo.html', catalogos=catalogos, productos=productos)


@view.route('/upload/<filename>')
def upload_file(filename):
    return send_from_directory(Config.UPLOAD_FOLDER,filename)

@view.route('/producto/update')
def update_producto(id):
    return render_template('/producto/update.html')

app/templates/base.html
{% from 'components.jinja' import catalogoForm, productoForm, formAuth, form_login, tabla %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <style>
        .masonry {
            columns: 5;
            column-gap: 1rem;
        }
        .masonry-item {
            display: inline-block;
            margin-bottom: 1rem;
            width: 100%;
        }
        @media (max-width: 1024px) {
            .masonry {
                columns: 4;
            }
        }
        @media (max-width: 768px) {
            .masonry {
                columns: 3;
            }
        }
        @media (max-width: 640px) {
            .masonry {
                columns: 2;
            }
        }
    </style>
</head>
<body class="p-2">
    {% block content %}
    {% endblock %}
</body>
</html>

app/templates/catalogo.html
{% extends 'base.html' %}
{% block content %}
<div class="w-full h-screen">
    <h1>Categorias</h1>
    <div class="flex w-full">
        {% for catalogo in catalogos %}
            <div class="w-full relative flex  justify-center items-center">
                <h1 class="absolute">{{catalogo.titulo }}</h1>
                <img class="w-40 h-20 object-cover rounded-md "  src="{{ url_for('view.upload_file', filename=catalogo.portada) }}" alt="" srcset="">
            </div>
        {% endfor%}
    </div>
    <h1 class="text-3xl font-bold mb-4">Productos</h1>
    <div class="masonry">
        {% for producto in productos %}
        <div class="masonry-item">
            <img  class="w-full h-auto rounded-lg    object-cover mb-2" src="{{ url_for('view.upload_file', filename=producto.portada)}}" alt="" srcset="">
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

app/templates/components.jinja
{%- macro catalogoForm(action_url) -%}
    <form class="" action="{{action_url}}">
        <div class="">
            <input type="text" value="{{catalogo.titulo}}">
        </div>
        <div>
            <input type="text" value="{{catalogo.detalle}}">
        </div>
        <div>
            <input type="file" value="{{catalogo.portada}}">
        </div>
    </form>
{%- endmacro -%}

{%- macro productoForm(action_url, catalogos) -%}
<div class="p-2 w-1/2">
    <h1>Crear Producto</h1>
<form class="grid grid-cols-1 gap-1 p-2 bg-white rounded-md"  action="{{action_url}}" method="post" enctype="multipart/form-data">
    <div class="border flex flex-col p-2">
       <label class="font-semibold text-sm" for="">Titulo</label> 
        <input class="border-b outline-none " name="titulo"  type="text">
    </div>
    <div class="border flex flex-col p-2">
        <label class="font-semibold text-sm"  for="">Detalles</label>
        <input class="border-b outline-none" name="detalle" type="text">
    </div>
    <div class="flex border flex-col p-2">
        <label class="font-semibold text-sm" for="">Catalogo</label>
        <select class="select-none" name="catalogo_id" id="">
            {% for catalogo in catalogos %}
            <option class="" value="{{catalogo.id}}">
                {{ catalogo.titulo }}
            </option>
            {% endfor %}
        </select>
    </div>
    <div class="">
        <label class="text-sm font-semibold" for="">Portada</label>
        <div class="flex justify-center border border-dashed">
            <div class="text-center">
                <svg class="mx-auto h-12 w-12 text-gray-300" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" data-slot="icon">
                    <path fill-rule="evenodd" d="M1.5 6a2.25 2.25 0 0 1 2.25-2.25h16.5A2.25 2.25 0 0 1 22.5 6v12a2.25 2.25 0 0 1-2.25 2.25H3.75A2.25 2.25 0 0 1 1.5 18V6ZM3 16.06V18c0 .414.336.75.75.75h16.5A.75.75 0 0 0 21 18v-1.94l-2.69-2.689a1.5 1.5 0 0 0-2.12 0l-.88.879.97.97a.75.75 0 1 1-1.06 1.06l-5.16-5.159a1.5 1.5 0 0 0-2.12 0L3 16.061Zm10.125-7.81a1.125 1.125 0 1 1 2.25 0 1.125 1.125 0 0 1-2.25 0Z" clip-rule="evenodd" />
                </svg>
                <div>
                    <label for="file-upload" class="relative cursor-pointer rounded-md bg-white font-semibold text-indigo-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-600 focus-within:ring-offset-2 hover:text-indigo-500">
                        <span>Subir Foto</span>
                        <input id="file-upload" name="portada" type="file" class="sr-only">
                      </label>
                </div>
            </div>
        </div>        
    </div>
    <div class="flex bg-green-700 p-2 justify-center text-white font-semibold">
        
        <button class="">Guardar</button>
    </div>
</form>
</div>
{%- endmacro -%}

{%- macro formAuth(url_for)-%}
    <div class="flex flex-col justify-center items-center w-full h-screen">
        
        <form class="grid rounded-md shadow-md  border p-3 w-80  grid-cols-1 gap-2" method="post" action="{{url_for}}"  >
            <div>
                <h1 class="text-2xl">Crear Cuenta</h1>
                <p class="uppercase text-sm font-semibold">Melamin</p>
            </div>
            <div class="">
                <label class="text-sm font-semibold"  for="">Usuario</label>
                <input class="w-full p-2  text-sm border outline-none rounded-md"  type="text" name="usuario" >
            </div>
            <div>
                <label class="text-sm font-semibold" for="">Correo</label>
                <input class="border p-2 text-sm w-full outline-none rounded-md" type="email" name="correo">
            </div>
            <div>
                <label class="text-sm font-semibold" for="">Clave</label>
                <input class="w-full p-2 text-sm border outline-none rounded-md" type="password" name="clave">
            </div>
            <div>
                <button class="bg-blue-500 w-full rounded-md text-sm font-semibold p-2" >Crear Cuenta</button>
            </div>
        </form>
    </div>
{%- endmacro -%}

{%- macro form_login() -%}
<div class="bg-black w-80 rounded-md bg-opacity-50 p-4 flex flex-col">
    <form class="grid grid-cols-1 gap-2" action="{{url_for('view.iniciar_sesion')}}" method="post">
        <div>
            <p class="text-sm text-white font-semibold">Bienvenido a</p>
            <h1 class="uppercase font-semibold text-2xl text-white">Melamin</h1>
        </div>
        <hr>
        <div class="">
            <input placeholder="usuario o correo" class="rounded-md font-semibold w-full p-3 border bg-gray-100 outline-none" name="usuario_correo" type="text">
        </div>
        <div class="">
            <input placeholder="clave" class="rounded-md font-semibold w-full p-3 bg-gray-100 border outline-none" name="clave" type="password">
        </div>
        <div class="w-80">
            <a href="" class="text-sm text-white font-semibold" >Recuperar cuenta</a>
        </div>
        
        <div class="pt-4">
            <button class="bg-white p-3 font-semibold w-full rounded-md" >Iniciar Sesion</button>
        </div>
        <hr>
        <div>
           <a class="text-white text-sm font-semibold" href="{{url_for('view.crear_cuenta')}}">Crear Cuenta</a> 
        </div>
    </form>
</div>
{%- endmacro -%} 

{%- macro tabla(items) -%}
    <table class="table-auto">
        <thead>
            <tr>
                <th>id</th>
                <th>titulo</th>
                <th>imagen</th>
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
                <tr>
                    <td> {{item.id}}</td>
                    <td> {{item.titulo}} </td>
                    <td>
                        <a href="{{url_for('view.upload_file', filename=item.portada)}}">{{item.portada}}</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{%- endmacro -%}

app/templates/index.html
{% extends 'base.html' %}
{% block content %}
<section class="w-full h-screen">
    <div class="w-full relative  h-full">
        <img class="w-full absolute h-full object-cover" src="{{url_for('static', filename='img/banner.jpg')}}" alt="" srcset="">
        <div class="flex w-full h-full justify-center items-center">
            <div class="w-3/4">

            </div>
            <div class="w-1/4 absolute">
                {{form_login()}}
            </div>
        </div>
        
    </div>  
</section>
{% endblock %}